version: '3.8'

services:
  invoices-pg:
    image: bitnami/postgresql:latest
    container_name: microservicos-01-invoices
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: invoices
    ports:
      - "5483:5432"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d

      